//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-D6K1SJRH\\MSSQLSERVER1;Initial Catalog=ql_cuahang_maytinh;Persi" +
            "st Security Info=True;User ID=sa;Password=1234567;Encrypt=True;TrustServerCertif" +
            "icate=True")]
        public string ql_cuahang_maytinhConnectionString1 {
            get {
                return ((string)(this["ql_cuahang_maytinhConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-D6K1SJRH\\MSSQLSERVER1;Initial Catalog=ql_cuahang_maytinh;Persi" +
            "st Security Info=True;User ID=sa;Password=1234567;Encrypt=False;TrustServerCerti" +
            "ficate=True")]
        public string ql_cuahang_maytinhConnectionString {
            get {
                return ((string)(this["ql_cuahang_maytinhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-D6K1SJRH\\MSSQLSERVER1;Initial Catalog=ql_cuahang_maytinh;Persi" +
            "st Security Info=True;User ID=sa;Password=1234567;Encrypt=True;TrustServerCertif" +
            "icate=True")]
        public string ql_cuahang_maytinhConnectionString2 {
            get {
                return ((string)(this["ql_cuahang_maytinhConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-D6K1SJRH\\MSSQLSERVER1;Initial Catalog=ql_cuahang_maytinh;Persi" +
            "st Security Info=True;User ID=sa;Password=1234567;Encrypt=True;TrustServerCertif" +
            "icate=True")]
        public string ql_cuahang_maytinhConnectionString3 {
            get {
                return ((string)(this["ql_cuahang_maytinhConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-D6K1SJRH\\MSSQLSERVER1;Initial Catalog=ql_cuahang_maytinh;User " +
            "ID=sa;Password=1234567;Encrypt=False")]
        public string ql_cuahang_maytinhConnectionString11 {
            get {
                return ((string)(this["ql_cuahang_maytinhConnectionString11"]));
            }
        }
    }
}
