<?xml version="1.0" encoding="utf-8"?><Database Name="ql_cuahang_maytinh" Class="QL_CuaHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-D6K1SJRH\MSSQLSERVER1;Initial Catalog=ql_cuahang_maytinh;Persist Security Info=True;User ID=sa;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="ql_cuahang_maytinhConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.taikhoankh" Member="taikhoankhs">
    <Type Name="taikhoankh">
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="google_id" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="khachhang_taikhoankh" Member="khachhang" ThisKey="MaKH" OtherKey="MaKH" Type="khachhang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chitietdathang" Member="chitietdathangs">
    <Type Name="chitietdathang">
      <Column Name="MaDH" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang_BH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="dathang_chitietdathang" Member="dathang" ThisKey="MaDH" OtherKey="MaDH" Type="dathang" IsForeignKey="true" />
      <Association Name="sanpham_chitietdathang" Member="sanpham" ThisKey="MaSP" OtherKey="MaSP" Type="sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chitietgiohang" Member="chitietgiohangs">
    <Type Name="chitietgiohang">
      <Column Name="MaGH" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="giohang_chitietgiohang" Member="giohang" ThisKey="MaGH" OtherKey="MaGH" Type="giohang" IsForeignKey="true" />
      <Association Name="sanpham_chitietgiohang" Member="sanpham" ThisKey="MaSP" OtherKey="MaSP" Type="sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chitietphieunhap" Member="chitietphieunhaps">
    <Type Name="chitietphieunhap">
      <Column Name="MaPN" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DonGiaNhap" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="sanpham_chitietphieunhap" Member="sanpham" ThisKey="MaSP" OtherKey="MaSP" Type="sanpham" IsForeignKey="true" />
      <Association Name="phieunhaphang_chitietphieunhap" Member="phieunhaphang" ThisKey="MaPN" OtherKey="MaPN" Type="phieunhaphang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chucvu" Member="chucvus">
    <Type Name="chucvu">
      <Column Name="MaCV" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="chucvu_NhanVien_ChucVu" Member="NhanVien_ChucVus" ThisKey="MaCV" OtherKey="MaCV" Type="NhanVien_ChucVu" />
      <Association Name="chucvu_PhanQuyen" Member="PhanQuyens" ThisKey="MaCV" OtherKey="MaCV" Type="PhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.danhgia" Member="danhgias">
    <Type Name="danhgia">
      <Column Name="madg" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masp" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="makh" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="noidungdanhgia" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ngaygiodanhgia" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sosao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhanh" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="khachhang_danhgia" Member="khachhang" ThisKey="makh" OtherKey="MaKH" Type="khachhang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="sanpham_danhgia" Member="sanpham" ThisKey="masp" OtherKey="MaSP" Type="sanpham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dathang" Member="dathangs">
    <Type Name="dathang">
      <Column Name="MaDH" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="MaKM" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TienKM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDatHang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang_TT" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang_DH" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="transaction_id" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="dathang_chitietdathang" Member="chitietdathangs" ThisKey="MaDH" OtherKey="MaDH" Type="chitietdathang" />
      <Association Name="khachhang_dathang" Member="khachhang" ThisKey="MaKH" OtherKey="MaKH" Type="khachhang" IsForeignKey="true" />
      <Association Name="khuyenmai_dathang" Member="khuyenmai" ThisKey="MaKM" OtherKey="MaKM" Type="khuyenmai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.giohang" Member="giohangs">
    <Type Name="giohang">
      <Column Name="MaGH" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="giohang_chitietgiohang" Member="chitietgiohangs" ThisKey="MaGH" OtherKey="MaGH" Type="chitietgiohang" />
      <Association Name="khachhang_giohang" Member="khachhang" ThisKey="MaKH" OtherKey="MaKH" Type="khachhang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.khachhang" Member="khachhangs">
    <Type Name="khachhang">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="khachhang_taikhoankh" Member="taikhoankhs" ThisKey="MaKH" OtherKey="MaKH" Type="taikhoankh" />
      <Association Name="khachhang_danhgia" Member="danhgias" ThisKey="MaKH" OtherKey="makh" Type="danhgia" />
      <Association Name="khachhang_dathang" Member="dathangs" ThisKey="MaKH" OtherKey="MaKH" Type="dathang" />
      <Association Name="khachhang_giohang" Member="giohangs" ThisKey="MaKH" OtherKey="MaKH" Type="giohang" />
    </Type>
  </Table>
  <Table Name="dbo.khuyenmai" Member="khuyenmais">
    <Type Name="khuyenmai">
      <Column Name="MaKM" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKM" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="khuyenmai_dathang" Member="dathangs" ThisKey="MaKM" OtherKey="MaKM" Type="dathang" />
    </Type>
  </Table>
  <Table Name="dbo.loaisp" Member="loaisps">
    <Type Name="loaisp">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="loaisp_sanpham" Member="sanphams" ThisKey="MaLoai" OtherKey="MaLoai" Type="sanpham" />
    </Type>
  </Table>
  <Table Name="dbo.ManHinh" Member="ManHinhs">
    <Type Name="ManHinh">
      <Column Name="MaManHinh" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenManHinh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="ManHinh_PhanQuyen" Member="PhanQuyens" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="PhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.nhanvien" Member="nhanviens">
    <Type Name="nhanvien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="HoatDong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="nhanvien_NhanVien_ChucVu" Member="NhanVien_ChucVus" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien_ChucVu" />
      <Association Name="nhanvien_banhang" Member="banhangs" ThisKey="MaNV" OtherKey="MaNV" Type="banhang" />
      <Association Name="nhanvien_phieunhaphang" Member="phieunhaphangs" ThisKey="MaNV" OtherKey="MaNV" Type="phieunhaphang" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien_ChucVu" Member="NhanVien_ChucVus">
    <Type Name="NhanVien_ChucVu">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCV" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="chucvu_NhanVien_ChucVu" Member="chucvu" ThisKey="MaCV" OtherKey="MaCV" Type="chucvu" IsForeignKey="true" />
      <Association Name="nhanvien_NhanVien_ChucVu" Member="nhanvien" ThisKey="MaNV" OtherKey="MaNV" Type="nhanvien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="MaCV" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaManHinh" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoQuyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="chucvu_PhanQuyen" Member="chucvu" ThisKey="MaCV" OtherKey="MaCV" Type="chucvu" IsForeignKey="true" />
      <Association Name="ManHinh_PhanQuyen" Member="ManHinh" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="ManHinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sanpham" Member="sanphams">
    <Type Name="sanpham">
      <Column Name="MaSP" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="GiaDeXuat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Tg_BaoHanh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Association Name="sanpham_chitietdathang" Member="chitietdathangs" ThisKey="MaSP" OtherKey="MaSP" Type="chitietdathang" />
      <Association Name="sanpham_chitietgiohang" Member="chitietgiohangs" ThisKey="MaSP" OtherKey="MaSP" Type="chitietgiohang" />
      <Association Name="sanpham_chitietphieunhap" Member="chitietphieunhaps" ThisKey="MaSP" OtherKey="MaSP" Type="chitietphieunhap" />
      <Association Name="sanpham_danhgia" Member="danhgias" ThisKey="MaSP" OtherKey="masp" Type="danhgia" />
      <Association Name="sanpham_chitietbanhang" Member="chitietbanhangs" ThisKey="MaSP" OtherKey="MaSP" Type="chitietbanhang" />
      <Association Name="loaisp_sanpham" Member="loaisp" ThisKey="MaLoai" OtherKey="MaLoai" Type="loaisp" IsForeignKey="true" />
      <Association Name="nhacungcap_sanpham" Member="nhacungcap" ThisKey="MaNCC" OtherKey="MaNCC" Type="nhacungcap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPhamFull" Member="SanPhamFulls">
    <Type Name="SanPhamFull">
      <Column Name="Masp" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="tensp" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="hinhanh" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="giadexuat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="giaban" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mota" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="tg_baohanh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Tenncc" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung_ChucVu" Member="NguoiDung_ChucVus">
    <Type Name="NguoiDung_ChucVu">
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="MaCV" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.banhang" Member="banhangs">
    <Type Name="banhang">
      <Column Name="MaBanHang" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NgayBan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="banhang_chitietbanhang" Member="chitietbanhangs" ThisKey="MaBanHang" OtherKey="MaBanHang" Type="chitietbanhang" />
      <Association Name="nhanvien_banhang" Member="nhanvien" ThisKey="MaNV" OtherKey="MaNV" Type="nhanvien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.phieunhaphang" Member="phieunhaphangs">
    <Type Name="phieunhaphang">
      <Column Name="MaPN" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="phieunhaphang_chitietphieunhap" Member="chitietphieunhaps" ThisKey="MaPN" OtherKey="MaPN" Type="chitietphieunhap" />
      <Association Name="nhanvien_phieunhaphang" Member="nhanvien" ThisKey="MaNV" OtherKey="MaNV" Type="nhanvien" IsForeignKey="true" />
      <Association Name="nhacungcap_phieunhaphang" Member="nhacungcap" ThisKey="MaNCC" OtherKey="MaNCC" Type="nhacungcap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chitietbanhang" Member="chitietbanhangs">
    <Type Name="chitietbanhang">
      <Column Name="MaBanHang" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="banhang_chitietbanhang" Member="banhang" ThisKey="MaBanHang" OtherKey="MaBanHang" Type="banhang" IsForeignKey="true" />
      <Association Name="sanpham_chitietbanhang" Member="sanpham" ThisKey="MaSP" OtherKey="MaSP" Type="sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DS_PhieuNhap" Member="DS_PhieuNhaps">
    <Type Name="DS_PhieuNhap">
      <Column Name="MaPN" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_ChiTietDatHang" Member="View_ChiTietDatHangs">
    <Type Name="View_ChiTietDatHang">
      <Column Name="MaDH" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_DonHang" Member="View_DonHangs">
    <Type Name="View_DonHang">
      <Column Name="MaDH" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDatHang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang_DH" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.nhacungcap" Member="nhacungcaps">
    <Type Name="nhacungcap">
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="nhacungcap_sanpham" Member="sanphams" ThisKey="MaNCC" OtherKey="MaNCC" Type="sanpham" />
      <Association Name="nhacungcap_phieunhaphang" Member="phieunhaphangs" ThisKey="MaNCC" OtherKey="MaNCC" Type="phieunhaphang" />
    </Type>
  </Table>
  <Function Name="dbo.InHoaDon" Method="InHoaDon">
    <Parameter Name="MaBanHang" Parameter="maBanHang" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="InHoaDonResult">
      <Column Name="MaBanHang" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InPhieuNhap" Method="InPhieuNhap">
    <Parameter Name="MaPN" Parameter="maPN" Type="System.String" DbType="VarChar(36)" />
    <ElementType Name="InPhieuNhapResult">
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DonGiaNhap" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaPN" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>